#!/usr/bin/env ruby
require "rubygems"

APP_PATH = File.expand_path('../../config/application',  __FILE__)
require File.expand_path("../../config/boot", __FILE__)
require 'jax/generators/commands'
JaxGenerator.start
