#ruby=2.0.0
#ruby-gemset=jax

source 'https://rubygems.org'

# Specify your gem's dependencies in jax-core.gemspec
gemspec

gem 'shader-script', :git => "git://github.com/sinisterchipmunk/shader-script.git"
gem 'jax', path: File.expand_path('..', File.dirname(__FILE__))
