class Jax.Mesh.LineCube extends Jax.Mesh.Lines
  constructor: (@halfSize = 0.5, @offset = [0,0,0]) ->
    if typeof @halfSize isnt 'number'
      super @halfSize
      @halfSize = @size / 2
    else
      super()
  
  init: (vertices, colors, normals, textures, indices) ->
    halfSize = @halfSize
    offset = @offset
    
    v = GLMatrix.vec3.create()
    # left quad
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1, 1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1, 1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1, 1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1,-1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1,-1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1,-1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1,-1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1, 1, 1], halfSize), offset)...
    # right quad
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1, 1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1, 1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1, 1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1,-1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1,-1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1,-1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1,-1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1, 1, 1], halfSize), offset)...
    # front horizontal
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1, 1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1, 1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1,-1, 1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1,-1, 1], halfSize), offset)...
    # back horizontal
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1, 1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1, 1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [-1,-1,-1], halfSize), offset)...
    vertices.push GLMatrix.vec3.add(v, GLMatrix.vec3.scale(v, [ 1,-1,-1], halfSize), offset)...

    true
