require File.expand_path('../config/application', __FILE__)
require 'jax/tasks/rake'

require 'jasmine'

module Jasmine
  class Config
    alias _start_server start_server
    def start_server(port = 8889)
      _start_server(8889)
    end
  end
end

load 'jasmine/tasks/jasmine.rake'
